spring:

  ### ??? ??? ??
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:

  ### JPA ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ### ?? ?? ? ???? ??
        # show_sql: true
        format_sql: true

## hibernate ??? <debug>
logging:
  level:
    org.hibernate.sql: debug
    # query bind data
    #org.hibernate.type: trace
